Revert "Bug 1260713 - Fix  RefCounted.h:106:50: error: no member named 'typeSize' in 'mozilla::KeyboardInfo' 0:22.21 uint32_t size = static_cast<const T*>(this)->typeSize(). r=smaug"
This reverts commit 2fc44072744e1815d94e1a2ed49de1aff28cf4be.